// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXxFBpq0AXEZTKiOoqP-Tk8C5ifHrbjhA',
    appId: '1:744859603320:web:4199d19a034cee5c24f88d',
    messagingSenderId: '744859603320',
    projectId: 'kuvore-8b7ad',
    authDomain: 'kuvore-8b7ad.firebaseapp.com',
    storageBucket: 'kuvore-8b7ad.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK1DM8VnF88y9118uSqvl-rdhBr1nyxGo',
    appId: '1:744859603320:android:6b2a021da04886ca24f88d',
    messagingSenderId: '744859603320',
    projectId: 'kuvore-8b7ad',
    storageBucket: 'kuvore-8b7ad.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXxFBpq0AXEZTKiOoqP-Tk8C5ifHrbjhA',
    appId: '1:744859603320:web:0ee5a1416bc51b8924f88d',
    messagingSenderId: '744859603320',
    projectId: 'kuvore-8b7ad',
    authDomain: 'kuvore-8b7ad.firebaseapp.com',
    storageBucket: 'kuvore-8b7ad.firebasestorage.app',
  );
}
